(set s (stack (of 10 20 30)))
(print (pop s))
(print (stack-len s))
(print (pop s))
(print (stack-len s))
(print (pop s))
(print (stack-len s))
(print (pop s))
(print (stack-len s))
(print (pop s))
(push s "Heller")
(print (stack-len s))
(print (pop s))
(print (stack-len s))
(print (pop s))
(print (stack-len s))